-- Techabanca Catalogue
-- Migration 0001: identity and tenancy foundation
--
-- Timestamps are stored as application-supplied UTC text values.
-- Internal INTEGER keys are never intended for public API exposure.
-- public_id values are generated by application code and are safe to expose.

CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    public_id TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL COLLATE NOCASE UNIQUE
        CHECK (length(email) BETWEEN 3 AND 320),
    password_hash TEXT NOT NULL
        CHECK (length(password_hash) > 0),
    display_name TEXT NOT NULL
        CHECK (length(trim(display_name)) BETWEEN 1 AND 120),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'suspended')),
    email_verified_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT
);

CREATE TABLE sessions (
    id INTEGER PRIMARY KEY,
    public_id TEXT NOT NULL UNIQUE,
    user_id INTEGER NOT NULL,
    token_hash TEXT NOT NULL UNIQUE
        CHECK (length(token_hash) > 0),
    expires_at TEXT NOT NULL,
    last_seen_at TEXT,
    created_at TEXT NOT NULL,
    revoked_at TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE organizations (
    id INTEGER PRIMARY KEY,
    public_id TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
        CHECK (length(trim(name)) BETWEEN 1 AND 160),
    country_code TEXT
        CHECK (country_code IS NULL OR length(country_code) = 2),
    timezone TEXT NOT NULL DEFAULT 'UTC'
        CHECK (length(trim(timezone)) BETWEEN 1 AND 64),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'suspended', 'closed')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT
);

CREATE TABLE organization_members (
    id INTEGER PRIMARY KEY,
    public_id TEXT NOT NULL UNIQUE,
    organization_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    role TEXT NOT NULL
        CHECK (role IN ('owner', 'admin', 'editor')),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'invited', 'suspended')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (organization_id, user_id)
);

CREATE TABLE business_profiles (
    organization_id INTEGER PRIMARY KEY,
    legal_or_display_name TEXT NOT NULL
        CHECK (length(trim(legal_or_display_name)) BETWEEN 1 AND 160),
    tagline TEXT,
    short_description TEXT,
    about_text TEXT,
    phone TEXT,
    whatsapp_number TEXT,
    email TEXT COLLATE NOCASE,
    address_line_1 TEXT,
    address_line_2 TEXT,
    city TEXT,
    state_region TEXT,
    postal_code TEXT,
    country_code TEXT
        CHECK (country_code IS NULL OR length(country_code) = 2),
    website_url TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
);

CREATE INDEX idx_sessions_user_id
    ON sessions(user_id);

CREATE INDEX idx_sessions_expires_at
    ON sessions(expires_at);

CREATE INDEX idx_organizations_status
    ON organizations(status);

CREATE INDEX idx_organization_members_user_status
    ON organization_members(user_id, status);

CREATE INDEX idx_organization_members_organization_status
    ON organization_members(organization_id, status);
